name: __projectname__
description: edit me
version: 0.0.1
author: __author__ <__email__>
homepage: __homepage__

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  path: '>=1.3.9 <2.0.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
